services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    
      - "15672:15672"  
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: "rabbitmq-diagnostics -q check_port_connectivity"
      interval: 1s
      timeout: 1s
      retries: 10
      start_period: 5s
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  weather_cron:
    build: 
      context: "./get_weather_info_cron"
      dockerfile: Dockerfile
    container_name: weather_cron
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always
    env_file:
      - .env

  weather_nest_api:
    build:
      context: "./weather_nest_api"
      dockerfile: Dockerfile.dev
    container_name: weather_nest_api
    volumes:
      - ./weather_nest_api:/app
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env 
    environment:
      NODE_ENV: development
      OPENAI_API_KEY: ${OPENAI_API_KEY}

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always

  weather_golang_worker:
    build: 
      context: "./weather_golang_worker"
      dockerfile: Dockerfile
    container_name: weather_worker
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672/
      QUEUE_NAME: weather-data
      NEST_API_URL: http://weather_nest_api:3000/api/weather/logs

  front-end:
    build:
      context: "./front-end"
      dockerfile: Dockerfile
    container_name: front-end
    volumes:
      - ./front-end:/app
    ports:
      - "5173:5173"
    restart: always

volumes:
  rabbitmq_data:


